import type { Metadata, Viewport } from "next";
import {
  Bricolage_Grotesque,
  Inter,
  JetBrains_Mono,
} from "next/font/google";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/next";
import { CompanionProviders } from "./companion/providers";
import "./globals.css";

// Premium typography via Next.js font optimization. Three CSS variables
// land on <html> and override the system-stack fallbacks declared in
// globals.css, so every component already reading var(--font-display)
// / var(--font-body) / var(--font-mono) picks the new faces up with
// zero per-component changes.
//
// • Bricolage Grotesque — variable display sans with a tight, confident
//   condensed feel. Replaces Impact while keeping the "sports
//   broadcast" energy.
// • Inter — body grotesque, premium reading rhythm.
// • JetBrains Mono — warm coding-style mono for tabular numbers,
//   eyebrows, and freshness readouts.
//
// `display: "swap"` lets the cream background paint immediately and
// swap to the web font once it loads — no FOIT, no white flash.

const displayFont = Bricolage_Grotesque({
  subsets: ["latin"],
  variable: "--font-display",
  display: "swap",
  // Variable font: pull the full weight + width axes so we can dial
  // both the condensed display headlines and the lighter weights some
  // small labels need. `next/font` requires omitting `weight` (or
  // setting it to "variable") whenever `axes` is present.
  axes: ["wdth"],
});

const bodyFont = Inter({
  subsets: ["latin"],
  variable: "--font-body",
  display: "swap",
  weight: ["400", "500", "600", "700", "800"],
});

const monoFont = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
  display: "swap",
  weight: ["500", "600", "700"],
});

export const metadata: Metadata = {
  title: "No Noise Scores",
  description: "Live scores for the sports moments that matter. No noise.",
  applicationName: "No Noise Scores",
  metadataBase: new URL("https://nonoisescores.app"),
  alternates: {
    canonical: "https://nonoisescores.app",
  },
  openGraph: {
    title: "No Noise Scores",
    description: "Live scores for the sports moments that matter. No noise.",
    url: "https://nonoisescores.app",
    siteName: "No Noise Scores",
    type: "website",
    // Next.js auto-resolves the `opengraph-image.tsx` route file in
    // app/ and injects it as the default OG image. No need to specify
    // images here — Next prepends the dynamic image automatically.
    // Per-page OG images can still override this when needed.
  },
  twitter: {
    card: "summary_large_image",
    title: "No Noise Scores",
    description: "Live scores for the sports moments that matter.",
    // Same: `twitter-image.tsx` is auto-resolved.
  },
  manifest: "/manifest.webmanifest",
  icons: {
    icon: [
      { url: "/favicon.svg", type: "image/svg+xml" },
      { url: "/favicon-32.png", type: "image/png", sizes: "32x32" },
    ],
    shortcut: "/favicon.svg",
    apple: { url: "/apple-touch-icon.png", sizes: "180x180" },
  },
  appleWebApp: {
    capable: true,
    title: "No Noise Scores",
    statusBarStyle: "default",
  },
  formatDetection: {
    telephone: false,
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  minimumScale: 1,
  viewportFit: "cover",
  // Light cream is the default — we don't auto-flip with
  // prefers-color-scheme. Users who pick Dark in Alerts & Notifications
  // get warm dark; everyone else gets cream regardless of OS setting.
  // Keeps the brand identity stable on first install.
  themeColor: "#f1ead8",
  colorScheme: "light",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${displayFont.variable} ${bodyFont.variable} ${monoFont.variable}`}
    >
      <head>
        {/* iOS apple-touch-startup-image — per-device cream splash that
            replaces the white flash on cold launch from home screen.
            Generated by scripts/generate-startup-images.mjs. Each entry
            targets a specific device width × height in CSS pixels with
            the device-pixel-ratio that matches iOS conventions. iPhones
            not covered here fall back to the manifest's background_color
            (also cream), so the worst case is still on-brand.
            (Phase 2.6.) */}
        <link
          rel="apple-touch-startup-image"
          href="/splash/iphone-16-pro-max-1320x2868.png"
          media="(device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="/splash/iphone-16-pro-1206x2622.png"
          media="(device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="/splash/iphone-15-pro-max-1290x2796.png"
          media="(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="/splash/iphone-15-pro-1179x2556.png"
          media="(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="/splash/iphone-12-13-14-pro-max-1284x2778.png"
          media="(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="/splash/iphone-12-13-14-1170x2532.png"
          media="(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="/splash/iphone-x-xs-11-pro-1125x2436.png"
          media="(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
        />

        {/* Theme bootstrap — Phase 19. Runs before paint to apply any
            manually-stored theme override (no-noise-theme = "light" |
            "dark"). Without this, a dark-mode user who manually picked
            light would briefly see dark on first paint. Tiny script
            kept inline so it never blocks render. */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var t=localStorage.getItem('no-noise-theme');if(t==='light'||t==='dark'){document.documentElement.setAttribute('data-theme',t)}}catch(e){}})();`,
          }}
        />
      </head>
      <body>
        <CompanionProviders>{children}</CompanionProviders>
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
